-- Phần 1: XÓA CƠ SỞ DỮ LIỆU CŨ VÀ TẠO MỚI

DROP DATABASE IF EXISTS NewsMartDB;
CREATE DATABASE IF NOT EXISTS NewsMartDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Sử dụng database
USE NewsMartDB;

-- Phần 2: TẠO CÁC BẢNG PHỤ TRỢ (Lookup Tables)
-- Bảng Roles: Định nghĩa các vai trò người dùng
CREATE TABLE Roles (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Description TEXT
);

-- Bảng OrderStatuses: Các trạng thái của đơn hàng
CREATE TABLE OrderStatuses (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Description TEXT
);

-- Bảng Topics: Các chủ đề cho bài viết
CREATE TABLE Topics (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Slug VARCHAR(255) NOT NULL UNIQUE,
    Description TEXT
);

-- Bảng PostTypes: Các loại bài viết
CREATE TABLE PostTypes (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Slug VARCHAR(255) NOT NULL UNIQUE,
    Description TEXT
);

-- Phần 3: TẠO CÁC BẢNG CHÍNH VÀ TÍCH HỢP KHÓA NGOẠI

-- Bảng Users
CREATE TABLE Users (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FullName VARCHAR(255) NOT NULL,
    Username VARCHAR(255) NOT NULL UNIQUE,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    RoleID INT NOT NULL,
    IsActive BOOLEAN DEFAULT TRUE,
    Address VARCHAR(255),
    Phone VARCHAR(20),
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (RoleID) REFERENCES Roles(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Bảng Categories
CREATE TABLE Categories (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Slug VARCHAR(255) NOT NULL UNIQUE,
    Description TEXT,
    ParentID INT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ParentID) REFERENCES Categories(ID) ON UPDATE CASCADE ON DELETE SET NULL
);

-- Bảng Brands
CREATE TABLE Brands (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Slug VARCHAR(255) NOT NULL UNIQUE,
    Address VARCHAR(255),
    Email VARCHAR(255),
    Contact VARCHAR(50),
    Description TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Bảng Products
CREATE TABLE Products (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CategoryID INT NOT NULL,
    BrandID INT NOT NULL,
    SalerID INT NOT NULL,
    Name VARCHAR(255) NOT NULL,
    Slug VARCHAR(255) NOT NULL UNIQUE,
    SKU VARCHAR(50) UNIQUE,
    Description TEXT,
    Price DECIMAL(18, 2) NOT NULL,
    StockQuantity INT NOT NULL DEFAULT 0,
    Discount DECIMAL(5, 2) DEFAULT 0.00,
    AverageRate DECIMAL(2, 1) DEFAULT 0.0,
    Favorites INT DEFAULT 0,
    Purchases INT DEFAULT 0,
    Views INT DEFAULT 0,
    IsActive BOOLEAN DEFAULT TRUE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CategoryID) REFERENCES Categories(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (BrandID) REFERENCES Brands(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (SalerID) REFERENCES Users(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Bảng ProductImages
CREATE TABLE ProductImages (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ProductID INT NOT NULL,
    URL VARCHAR(255) NOT NULL,
    IsMainImage BOOLEAN DEFAULT FALSE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ProductID) REFERENCES Products(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Bảng Orders
CREATE TABLE Orders (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    SalerID INT NOT NULL,
    OrderDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    OrderStatusID INT NOT NULL,
    TotalAmount DECIMAL(18, 2) NOT NULL,
    ShippingAddressID INT,
    PaymentMethod VARCHAR(50),
    PaymentStatus VARCHAR(50) DEFAULT 'Pending',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (SalerID) REFERENCES Users(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (OrderStatusID) REFERENCES OrderStatuses(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Bảng OrderItems
CREATE TABLE OrderItems (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    OrderID INT NOT NULL,
    ProductID INT NOT NULL,
    Quantity INT NOT NULL CHECK (Quantity > 0),
    PriceAtOrder DECIMAL(18, 2) NOT NULL,
    DiscountAtOrder DECIMAL(5, 2) DEFAULT 0.00,
    Subtotal DECIMAL(18, 2) NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (OrderID) REFERENCES Orders(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES Products(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Bảng Posts
CREATE TABLE Posts (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    AuthorID INT NOT NULL,
    ProductID INT,
    Title VARCHAR(255) NOT NULL,
    Slug VARCHAR(255) NOT NULL UNIQUE,
    Content LONGTEXT NOT NULL,
    PostTypeID INT NOT NULL,
    TopicID INT,
    Status VARCHAR(50) NOT NULL DEFAULT 'Pending',
    Views INT DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (AuthorID) REFERENCES Users(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (ProductID) REFERENCES Products(ID) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (PostTypeID) REFERENCES PostTypes(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (TopicID) REFERENCES Topics(ID) ON UPDATE CASCADE ON DELETE SET NULL
);

-- Bảng PostInteractions
CREATE TABLE PostInteractions (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PostID INT NOT NULL,
    UserID INT NOT NULL,
    InteractionType VARCHAR(50) NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY (PostID, UserID, InteractionType),
    FOREIGN KEY (PostID) REFERENCES Posts(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES Users(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Bảng Comments
CREATE TABLE Comments (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PostID INT NOT NULL,
    UserID INT NOT NULL,
    ParentCommentID INT,
    Content TEXT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (PostID) REFERENCES Posts(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES Users(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ParentCommentID) REFERENCES Comments(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Bảng Reviews
CREATE TABLE Reviews (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    ProductID INT NOT NULL,
    OrderID INT,
    Rating INT NOT NULL CHECK (Rating >= 1 AND Rating <= 5),
    Content TEXT,
    Status VARCHAR(50) DEFAULT 'Pending',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (ProductID) REFERENCES Products(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (OrderID) REFERENCES Orders(ID) ON UPDATE CASCADE ON DELETE SET NULL
);

-- Bảng Carts
CREATE TABLE Carts (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    ProductID INT NOT NULL,
    Quantity INT NOT NULL CHECK (Quantity > 0),
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY (UserID, ProductID),
    FOREIGN KEY (UserID) REFERENCES Users(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES Products(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Bảng ShippingInformation
CREATE TABLE ShippingInformation (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    OrderID INT NOT NULL UNIQUE,
    Address VARCHAR(255) NOT NULL,
    City VARCHAR(100),
    State VARCHAR(100),
    PostalCode VARCHAR(20),
    RecipientName VARCHAR(255) NOT NULL,
    RecipientPhone VARCHAR(20) NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (OrderID) REFERENCES Orders(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Bảng OrderTransactions
CREATE TABLE OrderTransactions (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    OrderID INT NOT NULL UNIQUE,
    PaymentMethod VARCHAR(50) NOT NULL,
    Amount DECIMAL(18, 2) NOT NULL,
    Currency VARCHAR(10) DEFAULT 'VND',
    Status VARCHAR(50) DEFAULT 'Pending',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (OrderID) REFERENCES Orders(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Bảng ProductFavorites
CREATE TABLE ProductFavorites (
    UserID INT NOT NULL,
    ProductID INT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (UserID, ProductID),
    FOREIGN KEY (UserID) REFERENCES Users(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES Products(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Bảng Notifications
CREATE TABLE Notifications (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Content TEXT NOT NULL,
    URL VARCHAR(255),
    IsRead BOOLEAN DEFAULT FALSE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Bảng Configurations
CREATE TABLE Configurations (
    SettingKey VARCHAR(100) PRIMARY KEY,
    SettingValue TEXT,
    Description VARCHAR(255),
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Bảng ShipperAssignments
CREATE TABLE ShipperAssignments (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    OrderID INT NOT NULL UNIQUE,
    ShipperID INT NOT NULL,
    AssignedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    PickedUpAt DATETIME,
    DeliveredAt DATETIME,
    FailedAt DATETIME,
    Notes TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (OrderID) REFERENCES Orders(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ShipperID) REFERENCES Users(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Bảng UserActivities
CREATE TABLE UserActivities (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT,
    ActionType VARCHAR(50) NOT NULL,
    Details TEXT,
    IPAddress VARCHAR(50),
    UserAgent TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(ID) ON UPDATE CASCADE ON DELETE SET NULL
);

